In [9]:
import torch

def combine_tensors(A, B):
    # 将A和B在最后一个维度上进行拼接
    C = torch.cat((A, B), dim=-1)
    C = torch.zeros_like(C)
    for i in range(C.shape[1]):
        if i % 2 == 0:
            C[:, i] = A[:, i//2]
        else:
            C[:, i] = B[:, i//2]
    return C

# 示例数据
batch_size = 3
input_dim = 4

# 创建示例张量A和B
A = torch.zeros(batch_size, input_dim)
B = torch.ones(batch_size, input_dim)

# 组合A和B
C = combine_tensors(A, B)

# 打印结果
print("A:", A.shape)
print(A)
print("B:", B.shape)
print(B)
print("C:", C.shape)
print(C)

A: torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
B: torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
C: torch.Size([3, 8])
tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 0., 1.]])


In [4]:
C = torch.cat((A, B), dim=-1)


In [5]:
# 将C的最后一个维度进行重新排列
C.reshape(*C.shape[:-1], -1, 2)

tensor([[[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]]])

In [6]:
C = torch.zeros_like(C)

In [7]:
C

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
import torch

def expand_tensor(tensor, n):
    expanded_tensor = tensor.repeat(n, 1)
    return expanded_tensor

# 示例数据
tensor = torch.tensor([[1, 0]])  # 要扩展的张量
n = 5  # 扩展的次数

# 扩展张量
expanded_tensor = expand_tensor(tensor, n)

print("原始张量:")
print(tensor)
print("扩展后的张量:")
print(expanded_tensor)

原始张量:
tensor([[1, 0]])
扩展后的张量:
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0]])


In [1]:
import torch
a = torch.tensor([[1, 1],[2, 0],[3, 0],[1, 0],[1, 0]],device='cuda')

In [25]:
for i,ai in enumerate(a):
    print(ai.nonzero(as_tuple=True)[0].tolist())

[0, 1]
[0]
[0]
[0]
[0]


In [2]:
a = torch.tensor([[[3]],[[4]],[[5]]],device='cuda')
a.expand(3,1,2)

tensor([[[3, 3]],

        [[4, 4]],

        [[5, 5]]], device='cuda:0')

In [1]:
import torch

















a = torch.zeros(2, 3, 4)
b = a.view(a.size(0), -1)
b.size()

torch.Size([2, 12])

In [1]:
import torch
import numpy as np
from scipy.spatial import ConvexHull
from sklearn import cluster,datasets                            

dataset = torch.load('/home/chizm/PatchART/data/MNIST/processed/train_attack_data_part.pt')
trainset = dataset[0].view(dataset[0].size()[0],-1).squeeze(1).detach().cpu()
trainset = trainset.numpy()
testset = dataset[1].view(dataset[1].size()[0],-1).squeeze(1).detach().cpu()
testset = testset.numpy()

In [2]:
trainset.shape

(192, 784)

In [115]:


params = {
    "n_clusters": 10,
}

spectral = cluster.SpectralClustering(
        n_clusters=params["n_clusters"],
        assign_labels="cluster_qr",
        eigen_solver="arpack",
        affinity="nearest_neighbors",
    )
clustering = spectral.fit(dataset)




In [116]:
clustering_predict = spectral.fit_predict(dataset)
clustering_predict.shape

(1000,)

In [124]:
clustering.labels_

array([7, 8, 0, 1, 7, 0, 2, 7, 3, 9, 2, 8, 5, 5, 9, 1, 9, 9, 6, 6, 2, 4,
       8, 9, 6, 8, 5, 4, 5, 4, 7, 6, 8, 9, 5, 8, 5, 7, 8, 8, 9, 6, 5, 9,
       2, 1, 3, 1, 5, 4, 0, 6, 3, 2, 6, 8, 3, 2, 7, 9, 5, 2, 7, 1, 2, 8,
       3, 9, 3, 0, 5, 9, 6, 8, 6, 7, 9, 2, 7, 0, 5, 8, 6, 8, 3, 4, 3, 7,
       9, 8, 5, 4, 6, 3, 4, 8, 9, 8, 5, 2, 3, 9, 6, 8, 7, 0, 6, 4, 4, 3,
       6, 6, 6, 3, 7, 9, 2, 8, 3, 9, 6, 2, 5, 4, 4, 8, 4, 4, 2, 0, 7, 1,
       5, 9, 6, 8, 7, 8, 2, 4, 3, 8, 3, 3, 7, 4, 6, 8, 6, 7, 7, 2, 3, 8,
       6, 0, 1, 1, 5, 7, 2, 4, 3, 9, 4, 6, 4, 8, 4, 7, 2, 2, 9, 1, 2, 8,
       0, 3, 7, 9, 7, 4, 6, 8, 2, 7, 7, 1, 6, 0, 6, 4, 8, 8, 2, 1, 3, 7,
       0, 3, 2, 4, 5, 3, 2, 6, 6, 2, 9, 3, 5, 1, 7, 3, 4, 4, 3, 1, 3, 9,
       6, 9, 5, 0, 2, 8, 8, 3, 5, 8, 2, 1, 2, 8, 4, 1, 5, 4, 2, 7, 7, 8,
       9, 1, 4, 0, 2, 4, 6, 9, 2, 7, 6, 0, 7, 4, 5, 9, 9, 8, 6, 0, 7, 4,
       9, 3, 1, 9, 8, 8, 5, 1, 6, 7, 2, 2, 3, 9, 6, 4, 3, 0, 5, 4, 3, 3,
       2, 7, 8, 1, 6, 7, 7, 0, 5, 4, 9, 0, 5, 8, 3,

In [138]:
clustering.labels_[clustering.labels_==2].shape

(99,)

In [131]:
testset

array([6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9, 8, 5, 9, 3, 3, 0, 7, 4,
       9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 8, 2, 9, 4, 4, 6, 4, 9, 7, 0, 9, 2,
       9, 5, 1, 5, 9, 1, 2, 3, 2, 3, 5, 9, 1, 7, 6, 2, 8, 2, 2, 5, 7, 4,
       1, 3, 4, 0, 4, 8, 0, 4, 3, 6, 8, 7, 6, 0, 9, 7, 5, 7, 2, 1, 1, 6,
       8, 9, 4, 1, 5, 2, 2, 9, 5, 4, 9, 7, 1, 8, 3, 9, 6, 0, 3, 1, 1, 2,
       6, 3, 5, 7, 6, 8, 3, 9, 5, 8, 5, 7, 6, 1, 1, 3, 1, 7, 4, 0, 6, 5,
       9, 3, 0, 9, 2, 4, 7, 1, 2, 9, 4, 2, 6, 1, 8, 9, 0, 6, 6, 7, 9, 9,
       8, 0, 1, 4, 4, 6, 7, 9, 2, 3, 7, 3, 2, 4, 1, 6, 2, 7, 5, 5, 7, 4,
       0, 2, 6, 3, 6, 4, 0, 4, 2, 6, 0, 0, 0, 0, 3, 1, 4, 4, 7, 5, 9, 6,
       9, 0, 7, 1, 4, 2, 7, 3, 6, 7, 5, 8, 4, 5, 5, 2, 7, 1, 1, 5, 6, 8,
       5, 8, 4, 0, 7, 9, 9, 2, 9, 7, 7, 8, 7, 4, 2, 6, 9, 1, 7, 0, 6, 4,
       2, 5, 7, 0, 7, 1, 0, 3, 7, 6, 5, 0, 6, 1, 5, 8, 8, 9, 0, 0, 4, 1,
       5, 2, 2, 3, 9, 4, 9, 5, 0, 6, 7, 7, 1, 8, 0, 2, 2, 0, 4, 1, 1, 2,
       7, 3, 7, 5, 0, 6, 6, 0, 4, 1, 2, 3, 4, 4, 6,

In [137]:
testset[testset==7].shape

(116,)

In [26]:
spectral.affinity_matrix_.shape

(1000, 1000)

In [112]:
Dbscan = cluster.DBSCAN(eps=6.23, min_samples=5).fit(trainset)
Dbscan.labels_

Dbscan.core_sample_indices_.shape

(435,)

In [114]:
labels = Dbscan.labels_

n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
n_noise_ = list(labels).count(-1)

print("Estimated number of clusters: %d" % n_clusters_)
print("Estimated number of noise points: %d" % n_noise_)


# 
# eps 有一个中间峰。当eps在中间峰右边，cluster点会减少；在中间峰左边时，cluster会随着eps的增大而减少. noise点会随着eps的增大而减少。



Estimated number of clusters: 11
Estimated number of noise points: 401


In [120]:
kmeans = cluster.KMeans(n_clusters=10, random_state=0, n_init="auto").fit(trainset)

kmeans.labels_

array([5, 7, 6, 0, 5, 3, 1, 5, 0, 6, 1, 7, 1, 1, 1, 0, 8, 8, 8, 9, 2, 0,
       7, 6, 9, 7, 4, 0, 4, 0, 5, 9, 1, 6, 1, 0, 4, 5, 7, 7, 0, 5, 1, 6,
       2, 0, 0, 3, 1, 0, 3, 8, 0, 6, 8, 7, 0, 7, 5, 3, 4, 5, 5, 0, 2, 1,
       0, 6, 1, 9, 4, 6, 9, 7, 8, 5, 0, 7, 3, 9, 1, 7, 8, 7, 3, 0, 0, 5,
       8, 7, 4, 0, 8, 3, 0, 7, 8, 7, 1, 3, 0, 6, 8, 7, 0, 9, 8, 0, 0, 3,
       5, 8, 8, 3, 5, 6, 1, 0, 1, 6, 8, 7, 4, 0, 0, 7, 0, 0, 2, 9, 5, 0,
       1, 6, 5, 7, 1, 7, 7, 0, 0, 7, 1, 3, 1, 0, 8, 7, 5, 3, 5, 7, 1, 7,
       8, 3, 0, 0, 4, 3, 2, 0, 3, 8, 0, 4, 0, 0, 0, 3, 1, 7, 6, 7, 2, 7,
       5, 3, 5, 6, 1, 0, 5, 3, 2, 3, 5, 3, 5, 9, 8, 0, 7, 3, 1, 0, 1, 3,
       9, 3, 2, 0, 4, 3, 2, 8, 5, 7, 1, 6, 4, 0, 5, 3, 0, 0, 0, 3, 0, 6,
       8, 6, 4, 9, 7, 7, 7, 3, 4, 7, 2, 0, 1, 7, 0, 3, 4, 0, 2, 3, 4, 7,
       6, 0, 0, 9, 6, 0, 5, 1, 7, 3, 8, 3, 5, 0, 4, 6, 6, 7, 8, 9, 3, 0,
       6, 3, 3, 0, 7, 7, 4, 3, 9, 3, 1, 7, 0, 8, 1, 0, 3, 9, 5, 0, 0, 3,
       2, 3, 1, 0, 9, 3, 5, 9, 1, 0, 3, 3, 1, 7, 0,

In [136]:
from sklearn.mixture import GaussianMixture
gmm = GaussianMixture(n_components=10).fit(trainset)
gmm.predict(trainset)

array([8, 6, 1, 2, 8, 4, 0, 8, 9, 1, 9, 9, 0, 0, 0, 2, 5, 5, 5, 4, 0, 7,
       0, 1, 4, 6, 3, 7, 3, 7, 8, 4, 0, 1, 0, 7, 3, 8, 6, 6, 7, 8, 0, 1,
       0, 7, 9, 2, 0, 7, 2, 5, 9, 6, 5, 0, 9, 6, 8, 5, 3, 8, 8, 2, 0, 0,
       7, 5, 9, 4, 3, 1, 4, 6, 5, 8, 9, 6, 8, 4, 0, 6, 5, 6, 2, 7, 9, 8,
       5, 6, 3, 7, 5, 2, 7, 6, 1, 6, 0, 2, 9, 1, 5, 6, 7, 4, 5, 7, 7, 2,
       4, 5, 8, 2, 8, 1, 0, 7, 9, 2, 5, 6, 3, 7, 7, 6, 7, 7, 0, 4, 8, 2,
       0, 2, 8, 6, 8, 6, 6, 7, 7, 6, 9, 2, 3, 7, 5, 6, 4, 2, 8, 6, 9, 6,
       5, 2, 9, 2, 3, 2, 0, 7, 1, 5, 7, 1, 7, 7, 7, 8, 9, 6, 9, 9, 0, 6,
       8, 2, 3, 1, 8, 7, 4, 2, 0, 2, 8, 2, 3, 4, 4, 7, 6, 2, 0, 2, 9, 8,
       4, 2, 0, 7, 3, 2, 0, 5, 5, 6, 9, 2, 3, 2, 8, 2, 7, 7, 9, 2, 9, 1,
       5, 1, 3, 4, 6, 6, 6, 2, 3, 6, 0, 2, 9, 6, 7, 2, 3, 7, 6, 2, 3, 6,
       1, 2, 7, 4, 1, 7, 8, 0, 6, 2, 5, 2, 8, 7, 3, 7, 1, 9, 5, 2, 2, 7,
       5, 2, 2, 7, 6, 6, 3, 2, 4, 8, 0, 6, 9, 5, 3, 7, 8, 4, 3, 7, 9, 2,
       0, 2, 9, 2, 4, 8, 8, 4, 0, 7, 1, 4, 0, 6, 9,

In [ ]:
import torch
import numpy as np



model = torch.load('/home/chizm/PatchART/pgd/model/pdg_net.pth')

In [22]:
import torch
import numpy as np
# from scipy.spatial import ConvexHull
from sklearn import cluster,datasets                            


dataset = torch.load('/home/chizm/PatchART/data/MNIST/processed/train_attack_data_part.pt')
train_label = dataset[1].view(dataset[1].size()[0],-1).squeeze(1)
# train_label = train_label.numpy()

feature = torch.load('/home/chizm/PatchART/data/MNIST/processed/train_feature_part.pt')
train_feature = feature.cpu().numpy()

train_attack_label = torch.load('/home/chizm/PatchART/data/MNIST/processed/train_attack_data_part_label.pt')






In [25]:
train_label.shape

torch.Size([1000])

In [26]:
feature.shape

torch.Size([1000, 32])

In [27]:
train_attack_label.shape

torch.Size([1000])

In [24]:
# compare the label of clustering and the label of train data, their mark is not the same
# kmeans_tensor_label =  torch.from_numpy(kmeans.labels_)
# # transfer to cuda
# kmeans_tensor_label = kmeans_tensor_label.cuda()
train_label_np = train_label.clone().detach().cpu().numpy()
print(kmeans.labels_[(kmeans.labels_==1) & (train_label_np == 4)].shape)
print(train_label[train_label == 4].shape)
print(kmeans.labels_[kmeans.labels_==1].shape)


(96,)
torch.Size([131])
(146,)


In [30]:
#TODO 2
print(kmeans.labels_[(kmeans.labels_==2) & (train_label_np == 7)].shape)
print(train_label[train_label == 7].shape)
print(kmeans.labels_[kmeans.labels_==2].shape)

(70,)
torch.Size([112])
(111,)


In [ ]:
#TODO 3

In [28]:
train_label_np = train_label.clone().detach().cpu().numpy()
print(kmeans.labels_[(kmeans.labels_==4) & (train_label_np == 9)].shape)
print(train_label[train_label == 9].shape)
print(kmeans.labels_[kmeans.labels_==4].shape)

(143,)
torch.Size([196])
(167,)


In [31]:
train_label_np = train_label.clone().detach().cpu().numpy()
print(kmeans.labels_[(kmeans.labels_==5) & (train_label_np == 1)].shape)
print(train_label[train_label == 1].shape)
print(kmeans.labels_[kmeans.labels_==5].shape)

(9,)
torch.Size([45])
(71,)


In [33]:
train_attack_label.clone().detach().cpu().numpy()

array([3, 4, 4, 3, 7, 9, 7, 1, 3, 9, 4, 9, 2, 8, 3, 7, 5, 8, 1, 4, 3, 1,
       3, 2, 9, 7, 5, 4, 7, 4, 1, 0, 5, 1, 3, 8, 4, 6, 3, 4, 2, 1, 3, 4,
       7, 7, 1, 6, 4, 5, 3, 1, 7, 3, 3, 4, 9, 4, 3, 9, 4, 4, 3, 1, 4, 8,
       3, 8, 3, 3, 9, 2, 5, 4, 9, 4, 4, 1, 0, 0, 5, 8, 4, 0, 2, 7, 8, 3,
       5, 9, 5, 3, 5, 2, 2, 4, 4, 8, 5, 9, 9, 7, 5, 4, 0, 2, 7, 4, 9, 8,
       3, 7, 6, 0, 2, 6, 4, 7, 6, 3, 8, 8, 2, 1, 3, 8, 4, 2, 1, 9, 8, 0,
       8, 3, 9, 1, 3, 3, 3, 5, 4, 7, 6, 3, 9, 9, 5, 8, 4, 7, 3, 4, 4, 4,
       1, 7, 5, 9, 3, 8, 5, 6, 7, 1, 7, 1, 9, 2, 7, 8, 4, 0, 8, 8, 3, 4,
       8, 4, 4, 5, 1, 3, 8, 7, 5, 5, 3, 2, 8, 9, 4, 0, 8, 4, 7, 2, 8, 5,
       5, 9, 9, 2, 9, 8, 5, 7, 7, 8, 5, 8, 3, 8, 3, 4, 1, 2, 5, 1, 7, 9,
       7, 1, 6, 4, 1, 0, 6, 0, 3, 2, 9, 3, 0, 8, 8, 7, 8, 8, 5, 4, 3, 3,
       8, 3, 8, 4, 1, 3, 5, 0, 8, 0, 2, 3, 8, 8, 3, 7, 1, 8, 9, 7, 9, 8,
       2, 8, 8, 1, 8, 2, 6, 8, 8, 8, 8, 9, 4, 3, 0, 1, 9, 4, 0, 3, 3, 0,
       3, 3, 8, 5, 5, 2, 4, 6, 9, 8, 9, 7, 0, 9, 6,

In [17]:
# using kmeans to cluster feature
kmeans = cluster.KMeans(n_clusters=10, random_state=0, n_init="auto").fit(train_feature)
kmeans.labels_




array([1, 4, 4, 5, 9, 2, 4, 2, 6, 1, 4, 8, 5, 7, 8, 9, 7, 0, 3, 1, 2, 2,
       5, 7, 4, 4, 4, 1, 4, 8, 5, 5, 3, 2, 5, 4, 1, 8, 3, 4, 5, 3, 8, 1,
       4, 2, 3, 0, 4, 4, 6, 3, 2, 6, 9, 8, 2, 1, 6, 1, 4, 4, 3, 2, 1, 7,
       2, 5, 3, 7, 1, 8, 3, 4, 4, 1, 4, 2, 9, 2, 3, 7, 4, 0, 9, 9, 4, 6,
       3, 8, 6, 6, 7, 2, 0, 4, 8, 7, 7, 1, 8, 1, 0, 4, 8, 9, 2, 4, 1, 4,
       3, 3, 8, 3, 2, 0, 8, 4, 7, 7, 3, 4, 2, 2, 5, 3, 8, 5, 5, 1, 5, 4,
       3, 5, 1, 2, 7, 2, 3, 3, 4, 4, 1, 6, 1, 1, 8, 4, 3, 4, 3, 8, 4, 8,
       2, 4, 4, 8, 6, 0, 0, 8, 2, 2, 9, 2, 2, 3, 9, 1, 4, 8, 0, 3, 6, 4,
       5, 1, 2, 3, 2, 5, 5, 9, 0, 0, 2, 2, 3, 1, 1, 6, 1, 4, 6, 3, 7, 8,
       6, 2, 2, 8, 6, 3, 7, 9, 9, 3, 6, 4, 5, 4, 3, 4, 3, 8, 6, 1, 3, 2,
       3, 3, 0, 1, 3, 6, 3, 6, 8, 8, 1, 5, 0, 3, 3, 2, 4, 5, 6, 3, 1, 9,
       3, 2, 8, 8, 2, 7, 0, 8, 7, 3, 8, 6, 6, 4, 7, 4, 3, 3, 4, 4, 1, 3,
       5, 0, 7, 5, 1, 6, 0, 4, 3, 4, 3, 2, 4, 6, 5, 6, 2, 8, 6, 6, 6, 5,
       6, 5, 3, 4, 6, 8, 4, 0, 1, 4, 2, 4, 5, 1, 8,

In [29]:
train_label
train_label_np

array([4, 9, 9, 1, 2, 7, 9, 7, 9, 4, 9, 4, 1, 9, 2, 2, 8, 6, 5, 1, 7, 7,
       2, 8, 7, 9, 7, 8, 9, 2, 2, 2, 8, 7, 1, 9, 3, 0, 8, 9, 3, 6, 2, 9,
       9, 2, 6, 5, 9, 9, 5, 8, 9, 5, 7, 6, 7, 9, 9, 4, 9, 9, 8, 7, 9, 5,
       7, 2, 2, 8, 4, 4, 8, 9, 5, 9, 9, 2, 7, 7, 1, 5, 9, 6, 7, 3, 9, 5,
       8, 6, 3, 5, 8, 7, 8, 9, 6, 5, 8, 4, 6, 4, 6, 9, 2, 7, 2, 9, 4, 9,
       8, 1, 4, 6, 7, 5, 6, 9, 8, 8, 6, 9, 5, 7, 2, 6, 6, 3, 2, 4, 2, 9,
       0, 2, 4, 8, 8, 7, 8, 8, 9, 9, 4, 5, 4, 4, 6, 9, 5, 9, 8, 9, 9, 2,
       3, 9, 9, 4, 5, 5, 6, 4, 2, 9, 2, 7, 7, 6, 2, 4, 9, 9, 5, 6, 5, 9,
       2, 9, 7, 8, 7, 2, 2, 3, 6, 3, 7, 7, 9, 4, 7, 3, 4, 9, 3, 8, 2, 0,
       3, 7, 7, 4, 5, 2, 0, 2, 0, 2, 3, 9, 2, 9, 8, 9, 6, 7, 3, 4, 1, 7,
       1, 6, 5, 9, 6, 3, 8, 3, 2, 7, 4, 2, 5, 6, 0, 9, 9, 2, 3, 1, 4, 7,
       1, 7, 4, 2, 7, 8, 6, 6, 3, 8, 4, 5, 3, 9, 8, 8, 6, 1, 3, 9, 4, 1,
       3, 5, 5, 2, 4, 5, 5, 9, 1, 9, 1, 7, 9, 5, 2, 3, 7, 0, 3, 9, 5, 3,
       9, 2, 1, 7, 3, 4, 9, 8, 4, 9, 7, 9, 2, 4, 4,

In [7]:
train_attack_label

tensor([3, 4, 4, 3, 7, 9, 7, 1, 3, 9, 4, 9, 2, 8, 3, 7, 5, 8, 1, 4, 3, 1, 3, 2,
        9, 7, 5, 4, 7, 4, 1, 0, 5, 1, 3, 8, 4, 6, 3, 4, 2, 1, 3, 4, 7, 7, 1, 6,
        4, 5, 3, 1, 7, 3, 3, 4, 9, 4, 3, 9, 4, 4, 3, 1, 4, 8, 3, 8, 3, 3, 9, 2,
        5, 4, 9, 4, 4, 1, 0, 0, 5, 8, 4, 0, 2, 7, 8, 3, 5, 9, 5, 3, 5, 2, 2, 4,
        4, 8, 5, 9, 9, 7, 5, 4, 0, 2, 7, 4, 9, 8, 3, 7, 6, 0, 2, 6, 4, 7, 6, 3,
        8, 8, 2, 1, 3, 8, 4, 2, 1, 9, 8, 0, 8, 3, 9, 1, 3, 3, 3, 5, 4, 7, 6, 3,
        9, 9, 5, 8, 4, 7, 3, 4, 4, 4, 1, 7, 5, 9, 3, 8, 5, 6, 7, 1, 7, 1, 9, 2,
        7, 8, 4, 0, 8, 8, 3, 4, 8, 4, 4, 5, 1, 3, 8, 7, 5, 5, 3, 2, 8, 9, 4, 0,
        8, 4, 7, 2, 8, 5, 5, 9, 9, 2, 9, 8, 5, 7, 7, 8, 5, 8, 3, 8, 3, 4, 1, 2,
        5, 1, 7, 9, 7, 1, 6, 4, 1, 0, 6, 0, 3, 2, 9, 3, 0, 8, 8, 7, 8, 8, 5, 4,
        3, 3, 8, 3, 8, 4, 1, 3, 5, 0, 8, 0, 2, 3, 8, 8, 3, 7, 1, 8, 9, 7, 9, 8,
        2, 8, 8, 1, 8, 2, 6, 8, 8, 8, 8, 9, 4, 3, 0, 1, 9, 4, 0, 3, 3, 0, 3, 3,
        8, 5, 5, 2, 4, 6, 9, 8, 9, 7, 0,

In [6]:
a = 377.83+30+504.29+30+499.39+30+498.34+30+350.52+30+220.2+30+349.70+30+307.08+30+185.69+30+457.44+30+420.84+30+405.62+30+206.31+395.05+30+424.17+30+441.53+30
a*0.8+28*0.8+18.2*0.9

5233.9800000000005

In [ ]:
import os
from pathlib import Path

RES_DIR = Path(__file__).resolve().parent.parent / 'results' / 'mnist' / 'repair' / 'debug'

lr = [0.01, 0.005]
weight_decay = [0.0001, 0.00005]
kcoeff = [0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7]
support_loss = ['SmoothL1', 'L1', 'L2']
accuracy_loss = ['CE', 'MSE']
repair_radius = [0.01, 0.03, 0.05, 0.1, 0.15, 0.2]
record_dict = {}
for l in lr:
    record_dict[l] = {}
    for w in weight_decay:
        record_dict[l][w] = {}
        for k in kcoeff:
            record_dict[l][w][k] = {}
            for s in support_loss:
                record_dict[l][w][k][s] = {}
                for a in accuracy_loss:
                    record_dict[l][w][k][s][a] = {}
                    for r in repair_radius:
                        record_dict[l][w][k][s][a][r] = 0
                        

for file in os.listdir(RES_DIR):
    if file.endswith('log'):
        log_file_path = RES_DIR / file
        # file_name = file.split('-')
        lr, weight_decay, kcoeff, support_loss, accuracy_loss, repair_radius = file.split('-')[:-6]
        with open(log_file_path, 'r') as f:
            lines = f.readlines()
            test_acc = lines[-10].split(' ')[-1][:-1]
            record_dict[float(lr)][float(weight_decay)][float(kcoeff)][support_loss][accuracy_loss][float(repair_radius)] = float(test_acc)
            # for line in lines:
            #     if line.startswith('INFO:root:======== for network:5_2 and data:'):
            #         strings = line.split(' ')
            #         data = strings[4].split(':')[1]
            #         random = strings[7]

            #     if line.startswith('INFO:root:Marabou result'):
            #         tuples = line.split(':')[-1]
            #         result,time = tuples[1:-1].split(',')
            #         record_dict[data][random]['Marabou']['time'] = int(time[2:-2])
            #         record_dict[data][random]['Marabou']['result'] = result[1:-1]
            #     elif line.startswith('INFO:root:Delta-Marabou result'):
            #         tuples = line.split(':')[-1]
            #         result,time = tuples[1:-1].split(',')
            #         record_dict[data][random]['Delta']['time'] = int(time[2:-2])
            #         record_dict[data][random]['Delta']['result'] = result[1:-1]
f.close()

In [1]:
(137.9 + 136) * 0.9 + (28 + 318.53 + 30 + 395.96) * 0.8 

864.5020000000001